name: groupting
description: "친구들과 함께 그룹 소개팅을 즐길 수 있는 채팅 기반 매칭 앱"

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.0.0
  flutter_email_sender: ^6.0.2

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  cloud_functions: ^5.0.2

  # State Management
  provider: ^6.1.1

  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  image: ^4.1.7

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

  # Utils
  intl: ^0.20.2
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^17.2.1+2
  http: ^1.1.0
  path_provider: ^2.1.1
  firebase_app_check: ^0.3.2+10
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0


flutter:
  uses-material-design: true

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    min_sdk_android: 21

# 스플래시 화면 설정
flutter_native_splash:
  color: "#FFFFFF" # 배경색 (흰색)
  image: "assets/icon/icon.png" # 스플래시 중앙에 들어갈 로고 이미지
  branding: "assets/icon/icon.png" # (선택사항) 브랜드 로고
  color_dark: "#212121" # 다크모드 배경색
  image_dark: "assets/icon/icon.png" # 다크모드 이미지

  # Android 12 이상 (스플래시 API 대응)
  android_12:
    image: "assets/icon/icon.png"
    color: "#FFFFFF"

  # 전체 화면 여부
  fullscreen: true